version: '3.8'

services:
  app_blue:
    image: ${BLUE_IMAGE}
    environment:
      - APP_POOL=blue
      - RELEASE_ID=${RELEASE_ID_BLUE}
    ports:
      - "8081:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthz"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  app_green:
    image: ${GREEN_IMAGE}
    environment:
      - APP_POOL=green
      - RELEASE_ID=${RELEASE_ID_GREEN}
    ports:
      - "8082:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthz"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  nginx:
    image: nginx:alpine
    ports:
      - "${PORT:-8080}:80"
    volumes:
      - ./nginx.conf.template:/etc/nginx/nginx.conf.template:ro
      - ./nginx-entrypoint.sh:/nginx-entrypoint.sh

    environment:
      - ACTIVE_POOL=${ACTIVE_POOL:-blue}
    command: ["/nginx-entrypoint.sh"]
    depends_on:
      app_blue:
        condition: service_healthy
      app_green:
        condition: service_healthy